### ISSUE TITLE
Auto-tagging API request failed: 403 Forbidden:

### ISSUE THREAD

**Issue by nandhu** [CoreFiling/autotagging-example#1]
Hi,
I was not able to run command **yarn start "<source path>\examples\lead-by-example-limited-2013-06-30.html"**.  I got the below mentioned error.
Auto-tagging API request failed: 403 Forbidden:
{"path":"/v1/taxonomies","exception":"org.springframework.security.access.AccessDeniedException","timestamp":1528186765801,"message":"Access is denied","status":403,"error":"Forbidden"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I have supplied user name (my email) and password. use this credential I can able access corefiling.com.
But I am getting "Access is denied" error when execute the command.
Am I missed anything?

Thanks.
Nanda

**Comment by davidtnorth** [comment]
Hi, please could you send an e-mail to me using dtn@corefiling.co.uk and confirming your e-mail address used for your CoreFiling account, and I will check into this for you.

**Comment by davidtnorth** [comment]
Confirmed via e-mail this is now fixed (permissions problem, no bug in the code)
